version: '3.8'

services:
  github-milestones-mcp:
    build: .
    image: github-milestones-mcp-server:latest
    stdin_open: true
    tty: true
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    # MCP servers run on stdio, so no port mapping needed
    restart: unless-stopped 